name: 'podcast_analytics'
version: '1.0.0'
config-version: 2

profile: 'podcast_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  podcast_analytics:
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
    intermediate:
      +materialized: view
      +docs:
        node_color: "orange"
    marts:
      +materialized: table
      +docs:
        node_color: "green"

vars:
  # Define analysis cutoff date - using static date for testing
  analysis_date: '2024-05-01'